// Clay Public Search API — closed value sets (enums) for the query language.
//
// Copied VERBATIM from Clay's search query reference (the "Field docs" section:
// companies `industry`, `company_size`, `annual_revenue`, `locations.country_name`
// and experience `seniority`). Enum fields only accept these exact strings with
// `=` / `in (...)` — an unknown value makes the whole search fail — so the query
// builder in ./clay-query.ts maps free text onto these lists and DROPS anything
// that doesn't match rather than sending it.
//
// If Clay adds/renames values, refresh these lists from the reference; nothing
// else needs to change.

// ── Company size buckets (`company_size`) ─────────────────────────────────
// Each bucket carries its numeric employee range so employeeMin/Max criteria
// can be mapped onto every bucket that overlaps the requested range.
export const CLAY_COMPANY_SIZE_BUCKETS: readonly { value: string; min: number; max: number }[] = [
  { value: '1', min: 1, max: 1 },
  { value: '2-10', min: 2, max: 10 },
  { value: '11-50', min: 11, max: 50 },
  { value: '51-200', min: 51, max: 200 },
  { value: '201-500', min: 201, max: 500 },
  { value: '501-1,000', min: 501, max: 1000 },
  { value: '1,001-5,000', min: 1001, max: 5000 },
  { value: '5,001-10,000', min: 5001, max: 10000 },
  { value: '10,001+', min: 10001, max: Number.POSITIVE_INFINITY },
]

// ── Annual revenue buckets (`annual_revenue`, USD) ────────────────────────
// Bucketed enum — Clay does NOT accept numeric comparisons on revenue. min/max
// are whole USD so a revenueMin criterion can select the covering buckets.
export const CLAY_REVENUE_BUCKETS: readonly { value: string; min: number; max: number }[] = [
  { value: '0-500K', min: 0, max: 500_000 },
  { value: '500K-1M', min: 500_000, max: 1_000_000 },
  { value: '1M-5M', min: 1_000_000, max: 5_000_000 },
  { value: '5M-10M', min: 5_000_000, max: 10_000_000 },
  { value: '10M-25M', min: 10_000_000, max: 25_000_000 },
  { value: '25M-75M', min: 25_000_000, max: 75_000_000 },
  { value: '75M-200M', min: 75_000_000, max: 200_000_000 },
  { value: '200M-500M', min: 200_000_000, max: 500_000_000 },
  { value: '500M-1B', min: 500_000_000, max: 1_000_000_000 },
  { value: '1B-10B', min: 1_000_000_000, max: 10_000_000_000 },
  { value: '10B-100B', min: 10_000_000_000, max: 100_000_000_000 },
  { value: '100B-1T', min: 100_000_000_000, max: Number.POSITIVE_INFINITY },
]

// ── Experience seniority (`experiences.any(... seniority ...)`) ───────────
export const CLAY_SENIORITIES = [
  'Founder',
  'Owner',
  'Board Member',
  'Partner',
  'C-suite',
  'VP',
  'Director',
  'Head',
  'Manager',
  'Senior',
  'Mid-level',
  'Entry',
  'Intern / In Training',
  'Unknown',
] as const

export type ClaySeniority = (typeof CLAY_SENIORITIES)[number]

// The "decision maker" set used when no role filter is given: senior leaders
// who can sign off a sponsorship. Matches the leadership values Clay's
// reference reserves for exec / decision-maker searches.
export const CLAY_LEADERSHIP_SENIORITIES: readonly ClaySeniority[] = [
  'Founder',
  'Owner',
  'Partner',
  'C-suite',
  'VP',
  'Director',
  'Head',
]

// ── Company industry (`industry`) — 457 values ──────────────────────────
export const CLAY_INDUSTRIES: readonly string[] = [
  'Abrasives and Nonmetallic Minerals Manufacturing',
  'Accessible Architecture and Design',
  'Accommodation Services',
  'Accounting',
  'Administration of Justice',
  'Administrative and Support Services',
  'Advertising Services',
  'Agricultural Chemical Manufacturing',
  'Agriculture, Construction, Mining Machinery Manufacturing',
  'Air, Water, and Waste Program Management',
  'Airlines and Aviation',
  'Alternative Dispute Resolution',
  'Alternative Medicine',
  'Ambulance Services',
  'Amusement Parks and Arcades',
  'Animal Feed Manufacturing',
  'Animation',
  'Animation and Post-production',
  'Apparel Manufacturing',
  'Apparel and Fashion',
  'Appliances, Electrical, and Electronics Manufacturing',
  'Architectural and Structural Metal Manufacturing',
  'Architecture and Planning',
  'Armed Forces',
  'Artists and Writers',
  'Arts and Crafts',
  'Audio and Video Equipment Manufacturing',
  'Automation Machinery Manufacturing',
  'Automotive',
  'Aviation & Aerospace',
  'Aviation and Aerospace Component Manufacturing',
  'Baked Goods Manufacturing',
  'Banking',
  'Bars, Taverns, and Nightclubs',
  'Bed-and-Breakfasts, Hostels, Homestays',
  'Beverage Manufacturing',
  'Biomass Electric Power Generation',
  'Biotechnology',
  'Biotechnology Research',
  'Blockchain Services',
  'Blogs',
  'Boilers, Tanks, and Shipping Container Manufacturing',
  'Book Publishing',
  'Book and Periodical Publishing',
  'Breweries',
  'Broadcast Media Production and Distribution',
  'Building Construction',
  'Building Equipment Contractors',
  'Building Finishing Contractors',
  'Building Materials',
  'Building Structure and Exterior Contractors',
  'Business Consulting and Services',
  'Business Content',
  'Business Intelligence Platforms',
  'Business Supplies and Equipment',
  'Capital Markets',
  'Caterers',
  'Chemical Manufacturing',
  'Chemical Raw Materials Manufacturing',
  'Child Day Care Services',
  'Chiropractors',
  'Civic and Social Organizations',
  'Civil Engineering',
  'Claims Adjusting, Actuarial Services',
  'Clay and Refractory Products Manufacturing',
  'Climate Data and Analytics',
  'Climate Technology Product Manufacturing',
  'Coal Mining',
  'Collection Agencies',
  'Commercial Real Estate',
  'Commercial and Industrial Equipment Rental',
  'Commercial and Industrial Machinery Maintenance',
  'Commercial and Service Industry Machinery Manufacturing',
  'Communications Equipment Manufacturing',
  'Community Development and Urban Planning',
  'Community Services',
  'Computer Games',
  'Computer Hardware',
  'Computer Hardware Manufacturing',
  'Computer Networking',
  'Computer Networking Products',
  'Computer and Network Security',
  'Computers and Electronics Manufacturing',
  'Conservation Programs',
  'Construction',
  'Construction Hardware Manufacturing',
  'Consumer Electronics',
  'Consumer Goods',
  'Consumer Goods Rental',
  'Consumer Services',
  'Cosmetics',
  'Cosmetology and Barber Schools',
  'Courts of Law',
  'Credit Intermediation',
  'Dairy',
  'Dairy Product Manufacturing',
  'Dance Companies',
  'Data Infrastructure and Analytics',
  'Data Security Software Products',
  'Defense & Space',
  'Defense and Space Manufacturing',
  'Dentists',
  'Design',
  'Design Services',
  'Desktop Computing Software Products',
  'Digital Accessibility Services',
  'Distilleries',
  'E-Learning',
  'E-Learning Providers',
  'Economic Programs',
  'Education',
  'Education Administration Programs',
  'Education Management',
  'Electric Lighting Equipment Manufacturing',
  'Electric Power Generation',
  'Electric Power Transmission, Control, and Distribution',
  'Electrical Equipment Manufacturing',
  'Electronic and Precision Equipment Maintenance',
  'Embedded Software Products',
  'Emergency and Relief Services',
  'Engineering Services',
  'Engines and Power Transmission Equipment Manufacturing',
  'Entertainment',
  'Entertainment Providers',
  'Environmental Quality Programs',
  'Environmental Services',
  'Equipment Rental Services',
  'Events Services',
  'Executive Offices',
  'Executive Search Services',
  'Fabricated Metal Products',
  'Facilities Services',
  'Farming, Ranching, Forestry',
  'Farming',
  'Fashion Accessories Manufacturing',
  'Financial Services',
  'Fine Art',
  'Fine Arts Schools',
  'Fire Protection',
  'Fisheries',
  'Flight Training',
  'Food & Beverages',
  'Food and Beverage Manufacturing',
  'Food and Beverage Retail',
  'Food and Beverage Services',
  'Food Production',
  'Footwear Manufacturing',
  'Forestry and Logging',
  'Freight and Package Transportation',
  'Fruit and Vegetable Preserves Manufacturing',
  'Fundraising',
  'Funds and Trusts',
  'Furniture',
  'Furniture and Home Furnishings Manufacturing',
  'Gambling Facilities and Casinos',
  'Geothermal Electric Power Generation',
  'Glass Product Manufacturing',
  'Glass, Ceramics and Concrete Manufacturing',
  'Golf Courses and Country Clubs',
  'Government Administration',
  'Government Relations',
  'Government Relations Services',
  'Graphic Design',
  'Ground Passenger Transportation',
  'HVAC and Refrigeration Equipment Manufacturing',
  'Health and Human Services',
  'Health, Wellness and Fitness',
  'Higher Education',
  'Highway, Street, and Bridge Construction',
  'Historical Sites',
  'Holding Companies',
  'Home Health Care Services',
  'Horticulture',
  'Hospitality',
  'Hospitals',
  'Hospitals and Health Care',
  'Hotels and Motels',
  'Household Appliance Manufacturing',
  'Household Services',
  'Household and Institutional Furniture Manufacturing',
  'Housing Programs',
  'Housing and Community Development',
  'Human Resources',
  'Human Resources Services',
  'Hydroelectric Power Generation',
  'IT Services and IT Consulting',
  'IT System Custom Software Development',
  'IT System Data Services',
  'IT System Design Services',
  'IT System Installation and Disposal',
  'IT System Operations and Maintenance',
  'IT System Testing and Evaluation',
  'IT System Training and Support',
  'Import and Export',
  'Individual and Family Services',
  'Industrial Automation',
  'Industrial Machinery Manufacturing',
  'Industry Associations',
  'Information Services',
  'Information Technology and Services',
  'Insurance',
  'Insurance Agencies and Brokerages',
  'Insurance Carriers',
  'Insurance and Employee Benefit Funds',
  'Interior Design',
  'International Affairs',
  'International Trade and Development',
  'Internet Marketplace Platforms',
  'Internet News',
  'Internet Publishing',
  'Investment Advice',
  'Investment Banking',
  'Investment Management',
  'Janitorial Services',
  'Landscaping Services',
  'Language Schools',
  'Laundry and Drycleaning Services',
  'Law Enforcement',
  'Law Practice',
  'Leasing Non-residential Real Estate',
  'Leasing Residential Real Estate',
  'Leather Product Manufacturing',
  'Legal Services',
  'Legislative Offices',
  'Leisure, Travel & Tourism',
  'Libraries',
  'Loan Brokers',
  'Luxury Goods and Jewelry',
  'Machinery Manufacturing',
  'Manufacturing',
  'Maritime',
  'Maritime Transportation',
  'Market Research',
  'Marketing Services',
  'Mattress and Blinds Manufacturing',
  'Measuring and Control Instrument Manufacturing',
  'Meat Products Manufacturing',
  'Mechanical or Industrial Engineering',
  'Media & Telecommunications',
  'Media Production',
  'Medical Devices',
  'Medical Equipment Manufacturing',
  'Medical Practices',
  'Medical and Diagnostic Laboratories',
  'Mental Health Care',
  'Metal Ore Mining',
  'Metal Treatments',
  'Metal Valve, Ball, and Roller Manufacturing',
  'Metalworking Machinery Manufacturing',
  'Military and International Affairs',
  'Mining',
  'Mobile Computing Software Products',
  'Mobile Food Services',
  'Mobile Gaming Apps',
  'Motor Vehicle Manufacturing',
  'Motor Vehicle Parts Manufacturing',
  'Movies and Sound Recording',
  'Movies, Videos and Sound',
  'Museums',
  'Museums, Historical Sites, and Zoos',
  'Music',
  'Musicians',
  'Nanotechnology Research',
  'Natural Gas Distribution',
  'Newspaper Publishing',
  'Non-profit Organization Management',
  'Non-profit Organizations',
  'Nonmetallic Mineral Mining',
  'Nonresidential Building Construction',
  'Nuclear Electric Power Generation',
  'Nursing Homes and Residential Care Facilities',
  'Office Administration',
  'Office Furniture and Fixtures Manufacturing',
  'Oil and Gas',
  'Oil, Gas, and Mining',
  'Online Audio and Video Media',
  'Online Media',
  'Online and Mail Order Retail',
  'Operations Consulting',
  'Optometrists',
  'Outpatient Care Centers',
  'Outsourcing and Offshoring Consulting',
  'Outsourcing/Offshoring',
  'Packaging and Containers',
  'Packaging and Containers Manufacturing',
  'Paint, Coating, and Adhesive Manufacturing',
  'Paper and Forest Product Manufacturing',
  'Paper and Forest Products',
  'Performing Arts',
  'Performing Arts and Spectator Sports',
  'Periodical Publishing',
  'Personal Care Product Manufacturing',
  'Personal Care Services',
  'Personal and Laundry Services',
  'Pet Services',
  'Pharmaceutical Manufacturing',
  'Philanthropic Fundraising Services',
  'Philanthropy',
  'Photography',
  'Physical, Occupational and Speech Therapists',
  'Physicians',
  'Plastics Manufacturing',
  'Plastics and Rubber Product Manufacturing',
  'Political Organizations',
  'Primary Metal Manufacturing',
  'Primary and Secondary Education',
  'Printing Services',
  'Professional Organizations',
  'Professional Services',
  'Professional Training and Coaching',
  'Program Development',
  'Public Assistance Programs',
  'Public Health',
  'Public Policy',
  'Public Policy Offices',
  'Public Relations and Communications Services',
  'Public Safety',
  'Radio and Television Broadcasting',
  'Rail Transportation',
  'Railroad Equipment Manufacturing',
  'Ranching',
  'Real Estate',
  'Real Estate Agents and Brokers',
  'Real Estate and Equipment Rental Services',
  'Recreational Facilities',
  'Religious Institutions',
  'Renewable Energy Equipment Manufacturing',
  'Renewable Energy Power Generation',
  'Renewable Energy Semiconductor Manufacturing',
  'Renewables & Environment',
  'Repair and Maintenance',
  'Research',
  'Research Services',
  'Residential Building Construction',
  'Restaurants',
  'Retail',
  'Retail Apparel and Fashion',
  'Retail Appliances, Electrical, and Electronic Equipment',
  'Retail Art Dealers',
  'Retail Art Supplies',
  'Retail Books and Printed News',
  'Retail Building Materials and Garden Equipment',
  'Retail Florists',
  'Retail Furniture and Home Furnishings',
  'Retail Gasoline',
  'Retail Groceries',
  'Retail Health and Personal Care Products',
  'Retail Luxury Goods and Jewelry',
  'Retail Motor Vehicles',
  'Retail Musical Instruments',
  'Retail Office Equipment',
  'Retail Office Supplies and Gifts',
  'Retail Pharmacies',
  'Retail Recyclable Materials & Used Merchandise',
  'Reupholstery and Furniture Repair',
  'Robotics Engineering',
  'Rubber Products Manufacturing',
  'Satellite Telecommunications',
  'School and Employee Bus Services',
  'Seafood Product Manufacturing',
  'Securities and Commodity Exchanges',
  'Security Guards and Patrol Services',
  'Security Systems Services',
  'Security and Investigations',
  'Semiconductor Manufacturing',
  'Semiconductors',
  'Services for Renewable Energy',
  'Services for the Elderly and Disabled',
  'Sheet Music Publishing',
  'Shipbuilding',
  'Shuttles and Special Needs Transportation Services',
  'Sightseeing Transportation',
  'Soap and Cleaning Product Manufacturing',
  'Social Networking Platforms',
  'Software Development',
  'Solar Electric Power Generation',
  'Sound Recording',
  'Space Research and Technology',
  'Specialty Trade Contractors',
  'Spectator Sports',
  'Sporting Goods',
  'Sporting Goods Manufacturing',
  'Sports Teams and Clubs',
  'Sports and Recreation Instruction',
  'Spring and Wire Product Manufacturing',
  'Staffing and Recruiting',
  'Steam and Air-Conditioning Supply',
  'Strategic Management Services',
  'Subdivision of Land',
  'Sugar and Confectionery Product Manufacturing',
  'Surveying and Mapping Services',
  'Taxi and Limousine Services',
  'Technical and Vocational Training',
  'Technology, Information and Internet',
  'Technology, Information and Media',
  'Telecommunications',
  'Telecommunications Carriers',
  'Telephone Call Centers',
  'Temporary Help Services',
  'Textile Manufacturing',
  'Theater Companies',
  'Think Tanks',
  'Tobacco',
  'Tobacco Manufacturing',
  'Translation and Localization',
  'Transportation Equipment Manufacturing',
  'Transportation Programs',
  'Transportation, Logistics, Supply Chain and Storage',
  'Transportation/Trucking/Railroad',
  'Travel Arrangements',
  'Truck Transportation',
  'Trusts and Estates',
  'Turned Products and Fastener Manufacturing',
  'Urban Transit Services',
  'Utilities',
  'Utilities Administration',
  'Utility System Construction',
  'Vehicle Repair and Maintenance',
  'Venture Capital and Private Equity Principals',
  'Veterinary',
  'Veterinary Services',
  'Vocational Rehabilitation Services',
  'Warehousing',
  'Warehousing and Storage',
  'Waste Collection',
  'Waste Treatment and Disposal',
  'Water Supply and Irrigation Systems',
  'Water, Waste, Steam, and Air Conditioning Services',
  'Wellness and Fitness Services',
  'Wholesale',
  'Wholesale Alcoholic Beverages',
  'Wholesale Apparel and Sewing Supplies',
  'Wholesale Appliances, Electrical, and Electronics',
  'Wholesale Building Materials',
  'Wholesale Chemical and Allied Products',
  'Wholesale Computer Equipment',
  'Wholesale Drugs and Sundries',
  'Wholesale Food and Beverage',
  'Wholesale Footwear',
  'Wholesale Furniture and Home Furnishings',
  'Wholesale Hardware, Plumbing, Heating Equipment',
  'Wholesale Import and Export',
  'Wholesale Luxury Goods and Jewelry',
  'Wholesale Machinery',
  'Wholesale Metals and Minerals',
  'Wholesale Motor Vehicles and Parts',
  'Wholesale Paper Products',
  'Wholesale Petroleum and Petroleum Products',
  'Wholesale Raw Farm Products',
  'Wholesale Recyclable Materials',
  'Wind Electric Power Generation',
  'Wine and Spirits',
  'Wineries',
  'Wireless Services',
  'Wood Product Manufacturing',
  'Writing and Editing',
  'Zoos and Botanical Gardens',
]

// ── Company HQ country (`locations.any(country_name ...)`) — 220 values ──
export const CLAY_COUNTRIES: readonly string[] = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bonaire, Saint Eustatius and Saba ',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'British Virgin Islands',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Curacao',
  'Cyprus',
  'Czechia',
  'Democratic Republic of the Congo',
  'Denmark',
  'Djibouti',
  'Dominican Republic',
  'East Timor',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Estonia',
  'Ethiopia',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Ivory Coast',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nepal',
  'Netherlands',
  'Netherlands Antilles',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pakistan',
  'Palestinian Territory',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Republic of the Congo',
  'Reunion',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Barthelemy',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Serbia and Montenegro',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten',
  'Slovakia',
  'Slovenia',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Svalbard and Jan Mayen',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'U.S. Virgin Islands',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
]
